// Interface automatically generated by schemas-to-ts

export interface ItemsTest {
  quantity?: number;
  itemId?: number;
}
export interface ItemsTest_Plain {
  quantity?: number;
  itemId?: number;
}

export interface ItemsTest_NoRelations {
  quantity?: number;
  itemId?: number;
}

