// Interface automatically generated by schemas-to-ts

import { Client } from '../../../client/content-types/client/client';
import { Supplier } from '../../../supplier/content-types/supplier/supplier';
import { ItemsTest } from '../../../../components/item/interfaces/ItemsTest';
import { Client_Plain } from '../../../client/content-types/client/client';
import { Supplier_Plain } from '../../../supplier/content-types/supplier/supplier';
import { ItemsTest_Plain } from '../../../../components/item/interfaces/ItemsTest';
import { ItemsTest_NoRelations } from '../../../../components/item/interfaces/ItemsTest';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Memo {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    client?: { data: Client };
    supplier?: { data: Supplier };
    amountPaid?: number;
    date?: Date;
    Items: ItemsTest[];
    memoOrInvoice?: string;
  };
}
export interface Memo_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client?: Client_Plain;
  supplier?: Supplier_Plain;
  amountPaid?: number;
  date?: Date;
  Items: ItemsTest_Plain[];
  memoOrInvoice?: string;
}

export interface Memo_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client?: number;
  supplier?: number;
  amountPaid?: number;
  date?: Date;
  Items: ItemsTest_NoRelations[];
  memoOrInvoice?: string;
}

export interface Memo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client?: AdminPanelRelationPropertyModification<Client_Plain>;
  supplier?: AdminPanelRelationPropertyModification<Supplier_Plain>;
  amountPaid?: number;
  date?: Date;
  Items: ItemsTest_Plain[];
  memoOrInvoice?: string;
}
