// Interface automatically generated by schemas-to-ts

import { Invoice } from '../../../invoice/content-types/invoice/invoice';
import { Memo } from '../../../memo/content-types/memo/memo';
import { User } from '../../../../common/schemas-to-ts/User';
import { Invoice_Plain } from '../../../invoice/content-types/invoice/invoice';
import { Memo_Plain } from '../../../memo/content-types/memo/memo';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Client {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    phone?: string;
    email?: string;
    address?: string;
    invoices: { data: Invoice[] };
    memos: { data: Memo[] };
    user?: { data: User };
  };
}
export interface Client_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phone?: string;
  email?: string;
  address?: string;
  invoices: Invoice_Plain[];
  memos: Memo_Plain[];
  user?: User_Plain;
}

export interface Client_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phone?: string;
  email?: string;
  address?: string;
  invoices: number[];
  memos: number[];
  user?: number;
}

export interface Client_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phone?: string;
  email?: string;
  address?: string;
  invoices: AdminPanelRelationPropertyModification<Invoice_Plain>;
  memos: AdminPanelRelationPropertyModification<Memo_Plain>;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
}
