// Interface automatically generated by schemas-to-ts

import { Client } from '../../../client/content-types/client/client';
import { Supplier } from '../../../supplier/content-types/supplier/supplier';
import { ItemsTest } from '../../../../components/item/interfaces/ItemsTest';
import { Client_Plain } from '../../../client/content-types/client/client';
import { Supplier_Plain } from '../../../supplier/content-types/supplier/supplier';
import { ItemsTest_Plain } from '../../../../components/item/interfaces/ItemsTest';
import { ItemsTest_NoRelations } from '../../../../components/item/interfaces/ItemsTest';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Invoice {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    date?: Date;
    client?: { data: Client };
    supplier?: { data: Supplier };
    amountPaid?: number;
    Items: ItemsTest[];
  };
}
export interface Invoice_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  date?: Date;
  client?: Client_Plain;
  supplier?: Supplier_Plain;
  amountPaid?: number;
  Items: ItemsTest_Plain[];
}

export interface Invoice_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  date?: Date;
  client?: number;
  supplier?: number;
  amountPaid?: number;
  Items: ItemsTest_NoRelations[];
}

export interface Invoice_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  date?: Date;
  client?: AdminPanelRelationPropertyModification<Client_Plain>;
  supplier?: AdminPanelRelationPropertyModification<Supplier_Plain>;
  amountPaid?: number;
  Items: ItemsTest_Plain[];
}
