// Interface automatically generated by schemas-to-ts

export enum Type {
  Sales = 'sales',
  Labor = 'labor',
  Misc = 'misc',}

export interface Item {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    inventory?: number;
    description?: string;
    unitPrice?: number;
    type?: Type;
  };
}
export interface Item_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  inventory?: number;
  description?: string;
  unitPrice?: number;
  type?: Type;
}

export interface Item_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  inventory?: number;
  description?: string;
  unitPrice?: number;
  type?: Type;
}

export interface Item_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  inventory?: number;
  description?: string;
  unitPrice?: number;
  type?: Type;
}
